spring:
  application:
    name: gateway

server:
  port: 8080

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-res
          uri: lb://ms-res
          predicates:
            - Path=/reviews/**
          filters:
            - StripPrefix=1

        - id: ms-res-swagger
          uri: lb://ms-res
          predicates:
            - Path=/ms-res/openapi/**
          filters:
            - StripPrefix=1

        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        - id: health-ms-res
          uri: lb://ms-res
          predicates:
            - Host=microservice-health.com:8080
            - Path=/health
          filters:
            - SetPath=/actuator/health

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app.eureka-server: eureka

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
  instance:
    prefer-ip-address: true
