FROM eclipse-temurin:17-jre-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el JAR ya empacado por Maven
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Opcional: para poder usar curl si lo necesitas para healthchecks internos
RUN apk add --no-cache curl

# Puerto típico, si quieres que se vea en docker ps (no es obligatorio)
EXPOSE 8888

# Arrancar el Spring Boot NORMAL: sin JarLauncher, sin capas raras
ENTRYPOINT ["java","-jar","/app/app.jar"]
